$ENV:APP_VRESION="1.0.0"
$ENV:APP_NAME="permission"
$ENV:REMOTE_ADDRESS="47.74.22.216"
docker build -t $ENV:APP_NAME":"$ENV:APP_VRESION -f Dockerfile .
docker tag $ENV:APP_NAME":"$ENV:APP_VRESION $ENV:REMOTE_ADDRESS":"5000/$ENV:APP_NAME":"$ENV:APP_VRESION
docker push $ENV:REMOTE_ADDRESS":"5000/$ENV:APP_NAME":"$ENV:APP_VRESION